---
title: Example
---
flowchart TB
    A[DataFrame \n fruits] <--lossless--> B[Neutral\nXdataset]
    B <--[ plants, quantity, price_level ]--> E[Xarray 1]
    B <--[ quantity, product ]--> F[Xarray 2]
