name: env-analysis
dependencies:
  - matplotlib-base
  - numpy
  - pandas
  - xarray
  - scipp
  - pre-commit
  - setuptools
  - pip:
      # relative to this file. Needs to be editable to be accepted.
      - -e ../..
      - ntv-pandas>=2.0.0
      - tabulate>=0.9.0
      - pdoc
